<a href="https://colab.research.google.com/github/mdshahilraja301/PandasTutorial/blob/main/Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas Series

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['A','B','C','D']
my_list = [1,2,3,4]
arr = np.array([3,4,5,6])
d = {'a':1,'b':2,'c':3,'d':4}

In [3]:
pd.Series(my_list)

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
pd.Series(my_list,index = labels)

A    1
B    2
C    3
D    4
dtype: int64

In [5]:
pd.Series(arr,index = labels)      #only 1D array is accepet here

A    3
B    4
C    5
D    6
dtype: int64

In [6]:
pd.Series(d)

a    1
b    2
c    3
d    4
dtype: int64